org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3

loom_version=1.18-SNAPSHOT
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3

moddev_version=2.0.147
neo_version=26.3.0.10-beta
minecraft_version_range=[26.3]

mod_id=spellcraft
mod_name=Spellcraft Prototype
mod_license=MIT
mod_version=0.1.0
mod_group=dev.spellcraft.prototype
